### ISSUE TITLE
tableviewcontroller 

### ISSUE THREAD

**Issue by jackpaster** [Blackjacx/SHSearchBar#16]
how can i implement this search bar in a table view controller

**Comment by jackpaster** [comment]
@Blackjacx how can i implement this search bar in a table view controller

**Comment by Blackjacx** [comment]
What exactly do you want to do? 

If your searchBar should scroll at the top of the UITableViewController just set it as the `tableHeaderView`. If you want to react on the searchBars behaviour you can implement the `SHSearchBarDelegate`to i.e. react in the searchBarDidBeginEditing (user tapped in the searchBar which triggers editing per default) or the searchBarShouldCancel (cancel button pressed) events. You can implement a background dimming with this behaviour (maybe prior filtering the tableViews content using the searchTest).

If you want it to be independent of the tableViews scrolling you need to work with child view controllers.
