### ISSUE TITLE
Can't Change Font

### ISSUE THREAD

**Issue by ethanfox** [Blackjacx/SHSearchBar#22]
Whenever I set the font of the search bar, the font does change when the view initially loads. But, after a second the font resets. The placeholder text remains the custom font, but the font of the text typed goes back to default.

**Comment by Blackjacx** [comment]
Hey @ethanfox,

can you tell me which version you are using and how exactly you set the font to the search bar? The thing is in the latest version 1.1.0 I do nothing with the font. So if you set it via `searchBar.textField.font = <your font>`everything should work fine. You can access the inner textField directly for now and thus can change all the properties as you like. But this will change in future releases.
