### ISSUE TITLE
Search bar set as title view in iOS 11

### ISSUE THREAD

**Issue by CeceXX** [Blackjacx/SHSearchBar#30]
I'm setting the search bar as the title view of my navigation bar, however this doesn't seem to be working nicely. The text field isn't as large as the search bar, everything shrinks down. I also tried to subclass a UIView [like this](https://stackoverflow.com/questions/44932084/ios-11-navigationitem-titleview-width-not-set) and add the search bar as a subview but things got a lot more weird. What can I do? 

![giphy](https://user-images.githubusercontent.com/10504710/32239808-e84b974e-be6b-11e7-96ad-d56d1d468436.gif)

**Comment by Blackjacx** [comment]
What exactly are your problems? Can you make a list? Then I can try to reproduce and fix them.

**Comment by CeceXX** [comment]
Hey Stefan, thanks for your comment. Basically the problem is that when the user starts typing text the width of the text field changes (becomes a lot thinner).

**Comment by CeceXX** [comment]
You can try to add the search bar as the title view of a navigation bar to reproduce this issue.

**Comment by Blackjacx** [comment]
OK, I'll try this out this evening :)

**Comment by CeceXX** [comment]
Did you ever manage to get around this issue?

**Comment by CeceXX** [comment]
I'll leave a donation if you find the issue

**Comment by CeceXX** [comment]
in your examples, you use the search bar in the view controller content view. how do you use it as a navigation item title view?

**Comment by Blackjacx** [comment]
Hey, sorry for the delay. At the moment I don't have much tie to work on my projects. Work consumes a lot and I was ill so I spent a lot time on my couch 🙃

Actually I didn't plan to use it there yet but now I thought it would be another very good example 😉 

I think I'll find time in December to have a look on this topic.

**Comment by CeceXX** [comment]
Thanks so much for the response. It's fine please take your time. Know any good other framework by any chance?

Cesare de Cal
App Developer – Freelance iOS Developer at Cesare.io

A  Milan, Italy M  +39 370 317 30 39  ( tel:+39%20370%20317%2030%2039 ) E  hi@cesare.io ( hi@cesare.io ) W  http://cesare.io ( http://cesare.io/ )

( http://facebook.com/cesare.decal ) ( http://us.linkedin.com/in/cesaredecal ) ( http://twitter.com/CesareDeCal )

**Comment by Blackjacx** [comment]
Why you don't use the standard UISearchBar (maybe in combination with UISearchController) which is made exactly for your purpose?

**Comment by CeceXX** [comment]
Fine, thanks so much for your help. I'll be using the default search bar.

**Comment by Blackjacx** [comment]
Hey @CeceXX , finally I found some time to check how you could use my search bar in the UINavigationBar. I extended the example app with that use-case. See https://github.com/Blackjacx/SHSearchBar/commit/7a493092b59d7d62c11f73cc8f5427374293e656 for details. All you need to do is implement your titleView class and add SHSearchBar maximized to it. Then implement intrinsicContentSize in that class as I did in https://github.com/Blackjacx/SHSearchBar/blob/develop/Example/iOS%20Example/SearchBarTitleView.swift. 

Then all this should work. If you like to implement the standard UISearchBar then you could have a look on my answer on StackOverflow on how to do it right: https://stackoverflow.com/a/47908688/971329

**Comment by CeceXX** [comment]
Cheers, I appreciate it! Although I've switched to the standard UISearchBar, thank you so much for keeping me updated on this.
