### ISSUE TITLE
'pod try SHSearchBar': build fails

### ISSUE THREAD

**Issue by richardtop** [Blackjacx/SHSearchBar#32]
![image](https://user-images.githubusercontent.com/8013017/35678329-8cfd44bc-075b-11e8-9be1-9fe226e7f8cf.png)

For some reason, it fails on "No such module SHSearchBar"

**Comment by Blackjacx** [comment]
Try to run the project. Xcode 9 has a bug where there are sticky error messages displayed but the build actually succeeds.

**Comment by richardtop** [comment]
It fails, actually:
![image](https://user-images.githubusercontent.com/8013017/35728652-eed8dee4-0814-11e8-861f-322e9237c681.png)
Maybe, it is related to the fact that I run `pod try` or, using latest Xcode Beta

**Comment by Blackjacx** [comment]
Ah okay, what happens when you execute `pod try` with the release Xcode?

**Comment by Blackjacx** [comment]
Hmmm good catch. I was curious and found out that the project does currently not work with pod try. I will fix that!

**Comment by richardtop** [comment]
@Blackjacx That would be nice, as this library is good for prototyping, when you need to get a custom SearchBar quickly. The UISearchBar is quite bad at customization...

**Comment by Blackjacx** [comment]
Thanks ;)

**Comment by Blackjacx** [comment]
So this should be fixed with https://github.com/Blackjacx/SHSearchBar/releases/tag/1.4.1

**Comment by richardtop** [comment]
@Blackjacx thanks!
