### ISSUE TITLE
Migrate to Swift 3

### ISSUE THREAD

**Issue by Blackjacx** [Blackjacx/SHSearchBar#4]

**Comment by ko0f** [comment]
This is actually quite urgent, as it's not possible to use this within Swift 3 dynamic framework projects.

**Comment by Blackjacx** [comment]
Fell free to integrate the SHSearchBar from the swift3 branch. I created it last week. It would be nice to receive feedback from you. Via Cocoapods you can integrate it like so:

`pod 'SHSearchBar', :git => 'https://github.com/Blackjacx/SHSearchBar.git'`

I Also updated the README.

**Comment by ko0f** [comment]
I would, but it's not possible to do that on a Cocoapods framework - 

http://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of

**Comment by Blackjacx** [comment]
Ahhh okay I see the issue. Thank you very much for this hint. I will merge the `swift3` branch tonight. You can update tomorrow 👍

**Comment by Blackjacx** [comment]
OK the new release is out. The integration of the framework should work now. Feel free to contact me in case of any problems.
