### ISSUE TITLE
Compilation Issues: Key is not a member of NSAttributedString, etc 

### ISSUE THREAD

**Issue by sudhamab** [Blackjacx/SHSearchBar#44]
Stefan, 

firstly kudos for building this Custom Search Bar! It's exactly what I was looking for and it's super slick, like in the Airbnb app.  Also I saw that it can be used with the UITableView so thats perfect.

However, I am getting some issues in compiling when integrating with my project as well as compiling the sample app. Attaching a screenshot

My Xcode version is 9.4.1 and I checked that the Swift Version in the targets for the Pod was 4.1. 
I cleared the app's derived data, then cleaned the code and rebuild but same issue. 

What could I be missing? Really looking forward to using this pod.

![build_errors_shsearchbar](https://user-images.githubusercontent.com/8850788/49644537-b9632900-fa3e-11e8-8c6d-bf99a31f448b.jpeg)

**Comment by Blackjacx** [comment]
Hey @sudhamab ,

sorry for the late answer. Actually the code is already ported to Swift 4.2 as you can infer from the badges on the top of the readme. This means you cannot use it when compiling for Swift 4.1. The errors mean that the API I use is new in Swift 4.2 and not supported by Swift 4.1. 

What you can do though is use an older version of the pod. Just change your entry for my pod in your podfile to the following:

```ruby
pod 'SHSearchBar', '~> 1.4.3'
```

This should install the latest version < 1.5.0 (where I switched to Swift 4.2). 

Tell me if this helped you :)
Bye

**Comment by sudhamab** [comment]
thanks a lot Stefan! yes it compiles now.  I can't wait to integrate it and will confirm if I am able to get it running as well.

**Comment by Blackjacx** [comment]
Glad I could help you. Reach out if you have any feature request :-)
