### ISSUE TITLE
Add support for apple silicon simulators

### ISSUE THREAD

**Issue by kunaljaypatel** [Blackjacx/SHSearchBar#60]
Hi,

Can you update this library to support developers using apple silicon based Macs? 

![Screenshot 2023-05-14 at 3 32 16 PM](https://github.com/Blackjacx/SHSearchBar/assets/43392095/77ab4e20-19e7-4591-9422-b791e58f4a7d)

For reference: 
https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon#Update-pre-compiled-libraries-from-vendors

Thank you!

**Comment by Blackjacx** [comment]
Why did you close this again?
